version: '3.5'
services:
  tc-tomcat:
    image: tomcat:9.0.4-jre9
    build: .
    ports:
      - "8090:8080"
    volumes:
      - ./classes/artifacts/Transcurrency_war_exploded:/usr/local/tomcat/conf/Transcurrency_war_exploded
      - type: bind
        source: ./logback
        target: /usr/local/tomcat/logs
  tc-data:
    image: mysql:5.7.21
    build: .
    volumes:
      - type: bind
        source: ./target/classes/application-mysqldev.yml
        target: /usr/local/data/application-mysqldev.yml
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3366"